name: Pipeline

on:
  push:
    branches:
      - '{{ cookiecutter.main_git_branch }}'
      - 'feature**'

env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ "{{" }} secrets.{{cookiecutter.pipeline_user_aws_access_key_id_variable_name}} {{ "}}" }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ "{{" }} secrets.{{cookiecutter.pipeline_user_aws_secret_access_key_variable_name}} {{ "}}" }}
  SAM_TEMPLATE: {{cookiecutter.sam_template}}
  TESTING_STACK_NAME: {{cookiecutter.testing_stack_name}}
  TESTING_PIPELINE_EXECUTION_ROLE: {{cookiecutter.testing_pipeline_execution_role}}
  TESTING_CLOUDFORMATION_EXECUTION_ROLE: {{cookiecutter.testing_cloudformation_execution_role}}
  TESTING_ARTIFACTS_BUCKET: {{cookiecutter.testing_artifacts_bucket}}
  {%- if cookiecutter.testing_ecr_repo %}
  TESTING_ECR_REPO: {{cookiecutter.testing_ecr_repo}}
  {% else %}
  // If there are functions with "Image" PackageType in your template,
  // uncomment the line below and add "--image-repository ${TESTING_ECR_REPO}" to
  // testing "sam package" and "sam deploy" commands.
  // TESTING_ECR_REPO = '0123456789.dkr.ecr.region.amazonaws.com/repository-name'
  {% endif -%}
  TESTING_REGION: {{cookiecutter.testing_region}}
  PROD_STACK_NAME: {{cookiecutter.prod_stack_name}}
  PROD_PIPELINE_EXECUTION_ROLE: {{cookiecutter.prod_pipeline_execution_role}}
  PROD_CLOUDFORMATION_EXECUTION_ROLE: {{cookiecutter.prod_cloudformation_execution_role}}
  PROD_ARTIFACTS_BUCKET: {{cookiecutter.prod_artifacts_bucket}}
  {%- if cookiecutter.prod_ecr_repo %}
  PROD_ECR_REPO: {{cookiecutter.prod_ecr_repo}}
  {% else %}
  // If there are functions with "Image" PackageType in your template,
  // uncomment the line below and add "--image-repository ${PROD_ECR_REPO}" to
  // prod "sam package" and "sam deploy" commands.
  // PROD_ECR_REPO = '0123456789.dkr.ecr.region.amazonaws.com/repository-name'
  {% endif -%}
  PROD_REGION: {{cookiecutter.prod_region}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # trigger the tests here
  
  build-and-deploy-feature:
    # this stage is triggered only for feature branches (feature*),
    # which will build the stack and deploy to a stack named with branch name.
    if: startsWith(github.ref, 'refs/heads/feature')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - run: sam build --template ${SAM_TEMPLATE} --use-container

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: {{ '${{ env.PIPELINE_USER_ACCESS_KEY_ID }}' }}
          aws-secret-access-key: {{ '${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}' }}
          aws-region: {{ '${{ env.TESTING_REGION }}' }}
          role-to-assume: {{ '${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}' }}
          role-session-name: feature-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to feature stack in the testing account
        run: |
          sam deploy --stack-name $(echo ${GITHUB_REF##*/} | tr -cd '[a-zA-Z0-9-]') \
            --capabilities CAPABILITY_IAM \
            --region ${TESTING_REGION} \
            --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
            {%- if cookiecutter.testing_ecr_repo %}
            --image-repository ${TESTING_ECR_REPO} \
            {%- endif %}
            --no-fail-on-empty-changeset \
            --role-arn ${TESTING_CLOUDFORMATION_EXECUTION_ROLE}
  
  build-and-package:
    if: github.ref == 'refs/heads/{{ cookiecutter.main_git_branch }}'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1

      - name: Build resources
        run: sam build --template ${SAM_TEMPLATE} --use-container

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: {{ '${{ env.PIPELINE_USER_ACCESS_KEY_ID }}' }}
          aws-secret-access-key: {{ '${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}' }}
          aws-region: {{ '${{ env.TESTING_REGION }}' }}
          role-to-assume: {{ '${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}' }}
          role-session-name: testing-packaging
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Upload artifacts to testing artifact buckets
        run: |
          sam package \
            --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
            {%- if cookiecutter.testing_ecr_repo %}
            --image-repository ${TESTING_ECR_REPO} \
            {%- endif %}
            --region ${TESTING_REGION} \
            --output-template-file packaged-testing.yaml

      - uses: actions/upload-artifact@v2
        with:
          name: packaged-testing.yaml
          path: packaged-testing.yaml
          retention-days: 365
          
      - name: Assume the prod pipeline user role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: {{ '${{ env.PIPELINE_USER_ACCESS_KEY_ID }}' }}
          aws-secret-access-key: {{ '${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}' }}
          aws-region: {{ '${{ env.PROD_REGION }}' }}
          role-to-assume: {{ '${{ env.PROD_PIPELINE_EXECUTION_ROLE }}' }}
          role-session-name: prod-packaging
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Upload artifacts to production artifact buckets
        run: |
          sam package \
            --s3-bucket ${PROD_ARTIFACTS_BUCKET} \
            {%- if cookiecutter.prod_ecr_repo %}
            --image-repository ${PROD_ECR_REPO} \
            {%- endif %}
            --region ${PROD_REGION} \
            --output-template-file packaged-prod.yaml

      - uses: actions/upload-artifact@v2
        with:
          name: packaged-prod.yaml
          path: packaged-prod.yaml
          retention-days: 365
    
  deploy-testing:
    if: github.ref == 'refs/heads/{{ cookiecutter.main_git_branch }}'
    needs: [build-and-package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - uses: actions/download-artifact@v2
        with:
          name: packaged-testing.yaml

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: {{ '${{ env.PIPELINE_USER_ACCESS_KEY_ID }}' }}
          aws-secret-access-key: {{ '${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}' }}
          aws-region: {{ '${{ env.TESTING_REGION }}' }}
          role-to-assume: {{ '${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}' }}
          role-session-name: testing-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to testing account
        run: |
          sam deploy --stack-name ${TESTING_STACK_NAME} \
            --template packaged-testing.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${TESTING_REGION} \
            --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
            {%- if cookiecutter.testing_ecr_repo %}
            --image-repository ${TESTING_ECR_REPO} \
            {%- endif %}
            --no-fail-on-empty-changeset \
            --role-arn ${TESTING_CLOUDFORMATION_EXECUTION_ROLE}
  
  integration-test:
    if: github.ref == 'refs/heads/{{ cookiecutter.main_git_branch }}'
    needs: [deploy-testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # trigger the integration tests here
  
  deploy-prod:
    if: github.ref == 'refs/heads/{{ cookiecutter.main_git_branch }}'
    needs: [integration-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - uses: actions/download-artifact@v2
        with:
          name: packaged-prod.yaml
      
      - name: Assume the prod pipeline user role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: {{ '${{ env.PIPELINE_USER_ACCESS_KEY_ID }}' }}
          aws-secret-access-key: {{ '${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}' }}
          aws-region: {{ '${{ env.PROD_REGION }}' }}
          role-to-assume: {{ '${{ env.PROD_PIPELINE_EXECUTION_ROLE }}' }}
          role-session-name: prod-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to production account
        run: |
          sam deploy --stack-name ${PROD_STACK_NAME} \
            --template packaged-prod.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${PROD_REGION} \
            --s3-bucket ${PROD_ARTIFACTS_BUCKET} \
            {%- if cookiecutter.prod_ecr_repo %}
            --image-repository ${PROD_ECR_REPO} \
            {%- endif %}
            --no-fail-on-empty-changeset \
            --role-arn ${PROD_CLOUDFORMATION_EXECUTION_ROLE}
