version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      # trigger the integration tests here
      - cd ${PROJECT_SUBFOLDER}
      - echo 'Running integration tests'
