version = 0.1

[{{cookiecutter.testing_stage_name}}]
[{{cookiecutter.testing_stage_name}}.global]
[{{cookiecutter.testing_stage_name}}.global.parameters]
stack_name = "{{cookiecutter.testing_stack_name}}"
s3_prefix = "{{cookiecutter.testing_stack_name}}"
s3_bucket = "{{cookiecutter.testing_artifacts_bucket}}"
template = "{{cookiecutter.sam_template}}"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
region = "{{cookiecutter.testing_region}}"
parameter_overrides = ""

[{{cookiecutter.testing_stage_name}}]
[{{cookiecutter.testing_stage_name}}.deploy]
[{{cookiecutter.testing_stage_name}}.deploy.parameters]
template = "packaged-test.yaml"


[{{cookiecutter.prod_stage_name}}]
[{{cookiecutter.prod_stage_name}}.global]
[{{cookiecutter.prod_stage_name}}.global.parameters]
stack_name = "{{cookiecutter.prod_stack_name}}"
s3_prefix = "{{cookiecutter.prod_stack_name}}"
s3_bucket = "{{cookiecutter.prod_artifacts_bucket}}"
template = "{{cookiecutter.sam_template}}"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
region = "{{cookiecutter.prod_region}}"
parameter_overrides = ""

[{{cookiecutter.prod_stage_name}}]
[{{cookiecutter.prod_stage_name}}.deploy]
[{{cookiecutter.prod_stage_name}}.deploy.parameters]
template = "packaged-prod.yaml"


[pipeline]
[pipeline.deploy]
[pipeline.deploy.parameters]
stack_name = "{{cookiecutter.monorepo_project_subfolder}}-pipeline"
s3_prefix = "{{cookiecutter.monorepo_project_subfolder}}-pipeline/"
resolve_s3 = true
template = "codepipeline.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
